name: sms_gateway
description: SMS gateway using personal Mobile

version: 1.0.4+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^2.4.0
  shared_preferences: ^0.5.2+1
  firebase_auth: ^0.11.1+6
  firebase_messaging: ^5.0.1+1
  cloud_firestore: ^0.12.1
  permission_handler: ^3.1.0
  uuid: ^2.0.1
  flutter_slidable: ^0.5.3
  url_launcher: ^5.0.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true
